name: CI/CD

on: 
  push: 
    paths: 
      - "mizlab_tools/**"
      - "tests"

jobs:
  build: 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8"]
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: ${{ matrix.python-version }}
      - name: Install Depends
        run: pip install -r requirements.txt
      - name: Tests
        run: python setup.py test

  deploy:
    needs: build 
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v2
      - name: Create new branch
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b docs
      - name: Set up Python 
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8 
      - name: Install sphinx and depends
        run: | 
          python -m pip install --upgrade pip
          pip install sphinx commonmark recommonmark sphinx_rtd_theme
          sphinx-apidoc -f -o source/mizlab_tools ./mizlab_tools
          sphinx-build -b html ./source ./docs
      - name: deploy
        run: |
          git config user.name = "github-actions"
          git config user.email = "github-actions[bot]@users.noreply.github.com"
          git add docs -f
          git commit -m "auto build by github actions" --allow-empty
          git push --set-upstream origin docs

